# Generated by Django 4.1.7 on 2023-03-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellingportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_degree', models.IntegerField(default=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellingportal.student')),
            ],
        ),
    ]
